local paths = require "session-mgr.paths"

describe("paths.escape", function()
  it("matches the legacy escaping", function()
    eq("%home%me%dev%mach", paths.escape "/home/me/dev/mach")
  end)
  it("normalises a trailing slash", function()
    eq("%home%me%dev", paths.escape "/home/me/dev/")
  end)
  it("hashes keys over 200 bytes, keeping them unique and bounded", function()
    local a = paths.escape("/x/" .. ("a"):rep(300))
    local b = paths.escape("/x/" .. ("a"):rep(299) .. "b")
    eq(200, #a)
    ok(a ~= b, "different long paths must not collide")
    eq(a, paths.escape("/x/" .. ("a"):rep(300)))
  end)
end)

describe("paths files", function()
  it("builds the session and index paths", function()
    eq("/r/%p/work.vim", paths.session_file("/r", "%p", "work"))
    eq("/r/%p/index.json", paths.index_file("/r", "%p"))
  end)
end)

describe("paths.display_path", function()
  it("makes paths home-relative", function()
    eq("~/dev/mach", paths.display_path("/home/me/dev/mach", "/home/me", 40))
    eq("~", paths.display_path("/home/me", "/home/me", 40))
  end)
  it("does not treat a sibling of home as under home", function()
    eq("/home/username/x", paths.display_path("/home/username/x", "/home/user", 40))
  end)
  it("truncates the middle and keeps the last component whole", function()
    local out = paths.display_path("/home/me/path/to/longish/nested/projectA", "/home/me", 24)
    eq("~/path/to/long…/projectA", out)
    eq(24, vim.fn.strdisplaywidth(out))
  end)
  it("degrades when even the last component does not fit", function()
    eq("…/projectA", paths.display_path("/a/b/projectA", nil, 5))
  end)
end)

describe("paths.is_under", function()
  it("accepts children and rejects siblings, parents and traversal", function()
    ok(paths.is_under("/r", "/r/%p/a.vim"))
    ok(not paths.is_under("/r", "/r2/a.vim"))
    ok(not paths.is_under("/r", "/r"))
    ok(not paths.is_under("/r", "/r/../etc/passwd"))
  end)
end)
