local validate = require "session-mgr.validate"

describe("validate.name", function()
  it("accepts ordinary names, spaces and unicode", function()
    eq("work", (validate.name "work"))
    eq("big refactor", (validate.name "  big refactor  "))
    eq("naïve-2", (validate.name "naïve-2"))
  end)
  it("strips a typed .vim so the extension is never doubled", function()
    eq("work", (validate.name "work.vim"))
    eq("work", (validate.name "work.VIM"))
  end)
  it("rejects every traversal shape", function()
    for _, bad in ipairs { "../x", "..", "a/b", "a\\b", "/etc/passwd", ".hidden", ".", "..vim" } do
      local name, err = validate.name(bad)
      eq(nil, name, bad)
      ok(err, bad)
    end
  end)
  it("rejects empty, control characters, over-long and non-strings", function()
    eq(nil, (validate.name ""))
    eq(nil, (validate.name "   "))
    eq(nil, (validate.name ".vim"))
    eq(nil, (validate.name "a\nb"))
    eq(nil, (validate.name "a\0b"))
    eq(nil, (validate.name(("x"):rep(101))))
    eq(nil, (validate.name(nil)))
  end)
end)
